# version.py — PlatformIO pre-build hook: stamp a firmware version into include/fw_version.h.
#
# Every build bumps a monotonic counter (version.txt) and records the active build target (PIOENV) plus
# the git short-hash, so the running firmware can report exactly which image it is over MQTT and the web
# UI. version.txt and the generated header are git-ignored (local, per-machine) — bump BASE_VERSION by
# hand for a real release; the build number climbs on its own whenever we rebuild after a change.
import os, subprocess, datetime

Import("env")  # noqa: F821  (injected by PlatformIO/SCons)

BASE_VERSION = "1.1"                       # major.minor — raise by hand for a release

proj         = env["PROJECT_DIR"]
counter_file = os.path.join(proj, "version.txt")
header_file  = os.path.join(proj, "include", "fw_version.h")

# --- monotonic build counter, persisted locally ---------------------------------------------------
build = 0
try:
    with open(counter_file) as f:
        build = int(f.read().strip())
except (OSError, ValueError):
    build = 0
build += 1
with open(counter_file, "w") as f:
    f.write(str(build))

# --- best-effort git provenance (blank-safe if git is missing / not a repo) -----------------------
def git(*args):
    try:
        return subprocess.check_output(["git", *args], cwd=proj,
                                       stderr=subprocess.DEVNULL).decode().strip()
    except Exception:
        return ""

ghash = git("rev-parse", "--short", "HEAD") or "nogit"
if git("status", "--porcelain"):
    ghash += "-dirty"

target  = env["PIOENV"]
# A release/CI build can pin the exact version via env (e.g. the git tag), overriding the local counter.
# Local builds leave FW_VERSION_OVERRIDE unset and keep the "BASE_VERSION.build" behaviour unchanged.
override = os.environ.get("FW_VERSION_OVERRIDE", "").strip().lstrip("v")
version  = override if override else "%s.%d" % (BASE_VERSION, build)
date     = datetime.datetime.now().strftime("%Y-%m-%dT%H:%M:%S")

print("version.py: fw %s  target=%s  git=%s" % (version, target, ghash))

with open(header_file, "w") as f:
    f.write(
        "// AUTO-GENERATED by version.py before every build. Do not edit; do not commit.\n"
        "#pragma once\n"
        '#define FW_VERSION      "%s"\n'
        '#define FW_BUILD_TARGET "%s"\n'
        "#define FW_BUILD_NUMBER %d\n"
        '#define FW_GIT_HASH     "%s"\n'
        '#define FW_BUILD_DATE   "%s"\n'
        % (version, target, build, ghash, date))
